
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CAST = 9;
  public static final int MASMAS = 28;
  public static final int UNARIO = 30;
  public static final int MENOSMENOS = 29;
  public static final int MULT = 25;
  public static final int CHAR = 4;
  public static final int ENTERO = 6;
  public static final int INT = 3;
  public static final int FOR = 19;
  public static final int CP = 13;
  public static final int MENORIGUAL = 35;
  public static final int NOT = 33;
  public static final int AND = 31;
  public static final int IGUAL = 38;
  public static final int CARACTER = 7;
  public static final int OR = 32;
  public static final int DIV = 26;
  public static final int IF = 17;
  public static final int MAYORIGUAL = 37;
  public static final int DIST = 39;
  public static final int EOF = 0;
  public static final int ASIG = 14;
  public static final int error = 1;
  public static final int COMA = 15;
  public static final int MENOS = 24;
  public static final int MENOR = 34;
  public static final int MOD = 27;
  public static final int IDENT = 2;
  public static final int CLL = 11;
  public static final int MAYOR = 36;
  public static final int REAL = 8;
  public static final int ELSE = 18;
  public static final int WHILE = 21;
  public static final int FLOAT = 5;
  public static final int ALL = 10;
  public static final int AP = 12;
  public static final int PRINT = 22;
  public static final int DO = 20;
  public static final int PYC = 16;
  public static final int MAS = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENT",
  "INT",
  "CHAR",
  "FLOAT",
  "ENTERO",
  "CARACTER",
  "REAL",
  "CAST",
  "ALL",
  "CLL",
  "AP",
  "CP",
  "ASIG",
  "COMA",
  "PYC",
  "IF",
  "ELSE",
  "FOR",
  "DO",
  "WHILE",
  "PRINT",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "MOD",
  "MASMAS",
  "MENOSMENOS",
  "UNARIO",
  "AND",
  "OR",
  "NOT",
  "MENOR",
  "MENORIGUAL",
  "MAYOR",
  "MAYORIGUAL",
  "IGUAL",
  "DIST"
  };
}

