
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CAST = 10;
  public static final int FORALL = 48;
  public static final int MASMAS = 25;
  public static final int UNARIO = 27;
  public static final int MENOSMENOS = 26;
  public static final int MULT = 22;
  public static final int CHAR = 4;
  public static final int ENTERO = 7;
  public static final int REPEAT = 42;
  public static final int INT = 3;
  public static final int DESPIZQ = 28;
  public static final int FOR = 38;
  public static final int CP = 16;
  public static final int NOT = 46;
  public static final int AND = 44;
  public static final int MENORIGUAL = 31;
  public static final int IGUAL = 34;
  public static final int IMPLICACION = 47;
  public static final int CARACTER = 8;
  public static final int OR = 45;
  public static final int DIV = 23;
  public static final int IF = 36;
  public static final int MAYORIGUAL = 33;
  public static final int DIST = 35;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int ASIG = 17;
  public static final int error = 1;
  public static final int COMA = 18;
  public static final int MENOS = 21;
  public static final int MENOR = 30;
  public static final int MOD = 24;
  public static final int IDENT = 2;
  public static final int BOOLFALSE = 11;
  public static final int CLL = 14;
  public static final int REAL = 9;
  public static final int MAYOR = 32;
  public static final int DESPDER = 29;
  public static final int TIMES = 43;
  public static final int ELSE = 37;
  public static final int WHILE = 40;
  public static final int FLOAT = 5;
  public static final int BOOLTRUE = 12;
  public static final int ALL = 13;
  public static final int AP = 15;
  public static final int PRINT = 41;
  public static final int DO = 39;
  public static final int PYC = 19;
  public static final int MAS = 20;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENT",
  "INT",
  "CHAR",
  "FLOAT",
  "BOOLEAN",
  "ENTERO",
  "CARACTER",
  "REAL",
  "CAST",
  "BOOLFALSE",
  "BOOLTRUE",
  "ALL",
  "CLL",
  "AP",
  "CP",
  "ASIG",
  "COMA",
  "PYC",
  "MAS",
  "MENOS",
  "MULT",
  "DIV",
  "MOD",
  "MASMAS",
  "MENOSMENOS",
  "UNARIO",
  "DESPIZQ",
  "DESPDER",
  "MENOR",
  "MENORIGUAL",
  "MAYOR",
  "MAYORIGUAL",
  "IGUAL",
  "DIST",
  "IF",
  "ELSE",
  "FOR",
  "DO",
  "WHILE",
  "PRINT",
  "REPEAT",
  "TIMES",
  "AND",
  "OR",
  "NOT",
  "IMPLICACION",
  "FORALL"
  };
}

