
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int X = 7;
  public static final int MENOSUNARIO = 6;
  public static final int MENOS = 3;
  public static final int CP = 10;
  public static final int EOLN = 12;
  public static final int POR = 4;
  public static final int EOF = 0;
  public static final int PYC = 11;
  public static final int MAS = 2;
  public static final int NUMERO = 13;
  public static final int ASIG = 8;
  public static final int DIV = 5;
  public static final int error = 1;
  public static final int AP = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MENOSUNARIO",
  "X",
  "ASIG",
  "AP",
  "CP",
  "PYC",
  "EOLN",
  "NUMERO"
  };
}

