

--EJECUTAR ESTO TRAS CUALQUIER CONSULTA, PARA EVITAR INFERENCIAS DE LAS CHACHES
ALTER SYSTEM FLUSH SHARED_POOL;            -- |
ALTER SYSTEM FLUSH BUFFER_CACHE;           -- |
-----------------------------------------------

SELECT COUNT(*) FROM PRUEBA WHERE CLAVE = 50000;
ALTER SYSTEM FLUSH SHARED_POOL;            -- |
ALTER SYSTEM FLUSH BUFFER_CACHE;           -- |
SELECT COUNT(*) FROM PRUEBA WHERE DISPERSO = 50000;
ALTER SYSTEM FLUSH SHARED_POOL;            -- |
ALTER SYSTEM FLUSH BUFFER_CACHE;           -- |
SELECT COUNT(*) FROM PRUEBA WHERE CONCENTRADO = 5;
ALTER SYSTEM FLUSH SHARED_POOL;            -- |
ALTER SYSTEM FLUSH BUFFER_CACHE;           -- |
SELECT COUNT(*) FROM PRUEBA WHERE IDISPERSO = 50000;
ALTER SYSTEM FLUSH SHARED_POOL;            -- |
ALTER SYSTEM FLUSH BUFFER_CACHE;           -- |
SELECT COUNT(*) FROM PRUEBA WHERE ICONCENTRADO = 5;
ALTER SYSTEM FLUSH SHARED_POOL;            -- |
ALTER SYSTEM FLUSH BUFFER_CACHE;           -- |
SELECT COUNT(*) FROM PRUEBA WHERE BCONCENTRADO = 5;
ALTER SYSTEM FLUSH SHARED_POOL;            -- |
ALTER SYSTEM FLUSH BUFFER_CACHE;           -- |

--5. 

--EL MAS LENTO ES DISPERSO = 50000
--EL MAS RAPIDO SELECT COUNT(*) FROM PRUEBA WHERE CLAVE = 50000;



--6. Ahora procederemos a observar el principal inconveniente de los índices, su
--penalización en operaciones de escritura que afecten atributos indexados.



UPDATE PRUEBA SET DISPERSO = DISPERSO + 7; 
ALTER SYSTEM FLUSH SHARED_POOL;            -- |
ALTER SYSTEM FLUSH BUFFER_CACHE;           -- |
--| |   2 |   TABLE ACCESS FULL| PRUEBA |      3 |    528K|   1031K|00:00:00.21 |    4678 |   1940 |
--            4904  consistent gets
--    18956288  physical read total bytes

UPDATE PRUEBA SET IDISPERSO = IDISPERSO + 7; 
ALTER SYSTEM FLUSH SHARED_POOL;            -- | --<------- [[[[[[   MÁS RAPIDO   ]]]]]]  
ALTER SYSTEM FLUSH BUFFER_CACHE;           -- |
--  |   2 |   TABLE ACCESS FULL| PRUEBA |      3 |    528K|   1046K|00:00:00.19 |    4745 |   2260 |
--         5040  consistent gets
--     20578304  physical read total bytes


--7 


CREATE INDEX IDX ON PRUEBA(IDISPERSO);

SELECT COUNT(*) FROM PRUEBA WHERE IDISPERSO BETWEEN 10000 AND 20000;
-- |*  2 |   INDEX RANGE SCAN| IDX  |      1 |      5 |      5 |00:00:00.01 |       3 |
--  68  consistent gets
-- 212992  physical read total bytes

--8
ALTER SYSTEM FLUSH SHARED_POOL;            -- |
ALTER SYSTEM FLUSH BUFFER_CACHE;           -- |

SELECT COUNT(*) FROM PRUEBA WHERE IDISPERSO+ICONCENTRADO BETWEEN 10000
AND 20000;
--|*  2 |   TABLE ACCESS FULL| PRUEBA |      1 |     25 |      5 |00:00:00.10 |    2266 |   1955 |
-- 2517  consistent gets
--  18923520  physical read total bytes

--9

CREATE INDEX FIX ON PRUEBA(IDISPERSO+CONCENTRADO);  

--10
ALTER SYSTEM FLUSH SHARED_POOL;            -- |
ALTER SYSTEM FLUSH BUFFER_CACHE;           -- |

SELECT COUNT(*) FROM PRUEBA WHERE IDISPERSO+ICONCENTRADO BETWEEN 10000
AND 20000;

--11
--TARDA MENOS YA QUE EL INDICE REDUCE EL TIEMPO DE EJECUCION Y EL USO DE RECURSOS
--12

ALTER SYSTEM FLUSH SHARED_POOL;            -- |
ALTER SYSTEM FLUSH BUFFER_CACHE;           -- |
UPDATE PRUEBA SET IDISPERSO = IDISPERSO + 7;
--13
--|   2 |   TABLE ACCESS FULL| PRUEBA |      1 |    528K|    500K|00:00:00.21 |    2266 |   2260 |
--  17455  consistent gets
--      55771136  physical read total bytes


